### ISSUE TITLE
Authentication Failed?

### ISSUE THREAD

**Issue by koraliap** [adlnet/xAPI-Android-Roses#21]
Hello, i have installed the App in my Android smartphone and try to connect it to my LRS (instance of ADL's LRS ). I ve put the LRS (..../xAPI/) in the corresponding field but it is not evident where i put the Authorization credentials (USER name and password) of my LRS.
My LRS is up and the msg i get from the APP is that "Authentication failed, please verify your username and password". My LRS also shows POST and GET actions that fail with error code 401, so they indeed try to communicate but fail to authenticate.
Any clues?!

**Comment by ljwolford** [comment]
Hello,

The first field in the settings is for your actor name, the next one is your account name, followed by the account homePage. It sounds liek you have the LRS endpoint correct, so that is followed by your LRS account name then your LRS account password. There's an active PR out where we'll try to make it more user-friendly. Thanks!

**Comment by ljwolford** [comment]
![screenshot_20170720-085651](https://user-images.githubusercontent.com/1183373/28418518-fcd04a7c-6d29-11e7-9cba-768b5a18b3b5.png)

I added a screenshot so it's easier to view. The bottom two field are the LRS auth fields that need to be correct in order to communicate with the LRS properly. The top fields are values inside of the statement.

**Comment by koraliap** [comment]
Thanks. The last field was not visible in my screen no matter what.
It communicates with my LRS !!! (an error code 500 is displayed, but statements are sent)

**Comment by koraliap** [comment]
**Thanks a lot for the immediate response!!!**
